apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: rucio-mirrormaker
spec:
  version: 3.5.0
  replicas: 5
  connectCluster: "target-cluster"
  clusters:
  - alias: "source-cluster"
    bootstrapServers: 134.79.23.221:9094
  - alias: "target-cluster"
    bootstrapServers: rucio-frdf-kafka-bootstrap:9092
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  mirrors:
  - sourceCluster: "source-cluster"
    targetCluster: "target-cluster"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
        replication.policy.separator: ""
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
        replication.policy.separator: ""
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
    topicsPattern: "BUTLER_FRDF_TEST*,DATA_TEST.*,OTHER_TOPIC*,IN2P3_*" 
  logging: 
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
